name = "cliff-sh"
main = "src/index.js"
compatibility_date = "2025-09-01"

routes = [
  { pattern = "cliff.sh/*", zone_name = "cliff.sh" },
  { pattern = "www.cliff.sh/*", zone_name = "cliff.sh" },
]
